apiVersion: v1
kind: Pod
metadata:
  name: transformer-md5
  annotations:
    communication_type: "hpull://"
    wait_timeout: 15s
spec:
  containers:
    - name: server
      image: localhost:5000/md5_server:v1
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      command: ['/code/server.py', '--listen', '0.0.0.0', '--port', '80']
