apiVersion: v1
kind: Pod
metadata:
  name: echo-go
  annotations:
    communication_type: ${COMMUNICATION_TYPE:-"\"hpull://\""}
    wait_timeout: 2m
spec:
  containers:
    - name: server
      image: aistore/transformer_echo_go:latest
      command: ['./echo', '-l', '0.0.0.0', '-p', '80']
      ports:
        - name: default
          containerPort: 80
      readinessProbe:
        httpGet:
          path: /health
          port: default
