apiVersion: v1
kind: Pod
metadata:
  name: ffmpeg-go
  annotations:
    # Values it can take ["hpull://","hpush://"]
    communication_type: ${COMMUNICATION_TYPE:-"\"hpull://\""}
    wait_timeout: 5m
    support_direct_put: "true"
spec:
  containers:
    - name: server
      image: aistorage/transformer_ffmpeg_go:latest
      imagePullPolicy: Always
      ports:
        - name: default
          containerPort: 8000
      command: ['./go_ffmpeg', '-l', '0.0.0.0', '-p', '8000']
      readinessProbe:
        httpGet:
          path: /health
          port: default
