apiVersion: v1
kind: Pod
metadata:
  name: tar2tf
  annotations:
    # Values it can take ["hpull://","hrev://","hpush://"]
    communication_type: ${COMMUNICATION_TYPE:-"\"hrev://\""}
    wait_timeout: 60s
spec:
  containers:
    - name: server
      image: ${DOCKER_REGISTRY_URL:-"localhost:5000"}/tar2tf:v1
      ports:
        - containerPort: 80
