apiVersion: v1
kind: Pod
metadata:
  name: tar2tf
  annotations:
    # Values it can take ["hpull://","hrev://","hpush://"]
    communication_type: ${COMMUNICATION_TYPE:-"\"hrev://\""}
    wait_timeout: 60s
spec:
  containers:
    - name: server
      image: aistore/tar2tf:latest

      # To enable conversion e.g.
      command: ['./tar2tf', '-l', '0.0.0.0', '-p', 80, '${OPTION_KEY}', '${OPTION_VALUE}']
      ports:
        - containerPort: 80
