apiVersion: v1
kind: Pod
metadata:
  name: tar2tf
spec:
  containers:
    - name: server
      annotations:
        # Values it can take ["hpull://","hrev://","hpush://"]
        communication_type: ${COMMUNICATION_TYPE:-"\"hpush://\""}
        wait_timeout: 30s
      image: ${DOCKER_REGISTRY_URL:-"localhost:5000"}/tar2tf:v1
      ports:
        - containerPort: 80
