apiVersion: v1
kind: Pod
metadata:
  name: tar2tf
spec:
  containers:
    - name: server
      annotations:
        communication_type: "hpush://"
        wait_timeout: 30s
      image: localhost:5000/tar2tf:v1
      ports:
        - containerPort: 80
