# https://github.com/NVIDIA/ais-etl/blob/main/transformers/keras_transformer/README.md
apiVersion: v1
kind: Pod
metadata:
  name: transformer-keras
  annotations:
    # Values `communication_type` can take are ["hpull://", "hrev://", "hpush://", "io://"].
    # Visit https://github.com/NVIDIA/aistore/blob/main/docs/etl.md#communication-mechanisms 
    communication_type: ${COMMUNICATION_TYPE:-"\"hpull://\""}
    wait_timeout: 10m
spec:
  containers:
    - name: server
      image: aistorage/transformer_keras:latest
      imagePullPolicy: Always
      ports:
        - name: default
          containerPort: 80
      command: ["gunicorn", "--bind", "0.0.0.0:80", "--workers", "12", "app:app"]

      env:
        - name: FORMAT
        # expected values - PNG, JPEG, etc
          value: ${FORMAT:-"JPEG"}
        - name: TRANSFORM
        # MANDATORY: expected json string parameter-value pairs. 
        # https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image/ImageDataGenerator#apply_transform
        # e.g. '{"theta":40, "brightness":0.8, "zx":0.9, "zy":0.9}'
          value:  ${TRANSFORM}
      readinessProbe:
        httpGet:
          path: /health
          port: default
