apiVersion: v1
kind: Pod
metadata:
  name: transformer-echo
  annotations:
    # Values it can take ["hpull://","hrev://","hpush://"]
    communication_type: ${COMMUNICATION_TYPE:-"\"hpull://\""}
    wait_timeout: 5m
spec:
  containers:
    - name: server
      image: aistorage/transformer_echo:latest
      imagePullPolicy: Always
      ports:
        - name: default
          containerPort: 8000
      command:
        - "gunicorn"
        - "main:app"
        - "--worker-class"
        - "uvicorn.workers.UvicornWorker"
        - "--workers"
        - "16"
        - "--bind"
        - "0.0.0.0:8000"
        - "--log-level"
        - "info"
        - "--env"
        - "UVICORN_CMD_ARGS=--ws-max-size=17179869184"
      # This is a health check endpoint which one should specify
      # for aistore to determine the health of the ETL container.
      readinessProbe:
        httpGet:
          path: /health
          port: default
