apiVersion: v1
kind: Pod
metadata:
  name: transformer-ffmpeg
  annotations:
    # Values it can take ["hpull://","hrev://","hpush://"]
    communication_type: ${COMMUNICATION_TYPE:-"\"hpull://\""}
    wait_timeout: 5m
spec:
  containers:
    - name: server
      image: aistorage/transformer_ffmpeg:latest
      imagePullPolicy: Always
      ports:
        - name: default
          containerPort: 80
      command: ['/code/server.py', '--listen', '0.0.0.0', '--port', '80']
      env:
      # FFMPEG_OPTIONS is a dictionary of FFMPEG options, which includes any additional arguments supported by `ffmpeg.output()`.
      # For more information, refer to https://ffmpeg.org/ffmpeg.html#Synopsis.
      - name: FFMPEG_OPTIONS
        value: ${FFMPEG_OPTIONS:-"{}"}
      readinessProbe:
        httpGet:
          path: /health
          port: default
