apiVersion: v1
kind: Pod
metadata:
  name: transformer-hello-world
  annotations:
    communication_type: ${COMMUNICATION_TYPE:-"\"hpush://\""}
    wait_timeout: 5m
spec:
  containers:
    - name: server
      image: aistorage/transformer_hello_world:latest
      imagePullPolicy: Always
      ports:
        - name: default
          containerPort: 8000
      command: ["python", "/code/hello_world_server.py"]
      readinessProbe:
        httpGet:
          path: /health
          port: default
      volumeMounts: # mounts the `arg_type="fqn"`
        - name: ais
          mountPath: /tmp/ais
  volumes:
    - name: ais
      hostPath:
        path: /tmp/ais
        type: Directory
