apiVersion: v1
kind: Pod
metadata:
  name: transformer-audio-manager
  annotations:
    # Values it can take ["hpull://","hrev://","hpush://"]
    communication_type: "hpull://"
    wait_timeout: 10m
spec:
  containers:
    - name: server
      image: aistorage/transformer_audio_manager:latest
      imagePullPolicy: Always
      ports:
        - name: default
          containerPort: 80
      command: ['/code/server.py', '--listen', '0.0.0.0', '--port', '80']
      readinessProbe:
        httpGet:
          path: /health
          port: default
      env:
        - name: AIS_ENDPOINT
          value: "http://<ais-proxy>:51080"
        - name: SRC_BUCKET
          value: "split_audio"
        - name: SRC_PROVIDER
          value: "ais"  
        - name: OBJ_PREFIX
          value: ""
        - name: OBJ_EXTENSION
          value: "wav"
        - name: ETL_NAME
          value: "<etl-name>"