apiVersion: v1
kind: Pod
metadata:
  name: transformer-audio-manager
  annotations:
    communication_type: "hpull://"
    wait_timeout: 10m
spec:
  containers:
    - name: server
      image: aistorage/transformer_audio_manager:latest
      imagePullPolicy: Always
      ports:
        - name: default
          containerPort: 8000
      command: ["uvicorn", "fastapi_server:fastapi_app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4", "--no-access-log"]
      readinessProbe:
        httpGet:
          path: /health
          port: default
      env:
        # AIS endpoint
        - name: AIS_ENDPOINT
          value: "http://<ais-proxy>:51080"
        # Bucket name of the audio files
        - name: SRC_BUCKET
          value: "<bucket-name>"
        # Provider of the audio files (ais, gcp, aws) 
        - name: SRC_PROVIDER
          value: "ais"
        # Prefix of the audio files
        - name: OBJ_PREFIX
          value: ""
        # Extension of the audio files
        - name: OBJ_EXTENSION
          value: "wav"
        # ETL Name of the Audio Splitter ETL you previously initialised
        - name: ETL_NAME
          value: "<etl-name>"
      # If using `arg_type=fqn`, ensure the `mountPath` matches the file system path 
      # where the objects are stored on AIStore targets. This allows the ETL container 
      # to access the files directly by absolute path.
  #     volumeMounts:
  #       - name: ais
  #         mountPath: /tmp/
  # volumes:
  #   - name: ais
  #     hostPath:
  #       path: /tmp/
  #       type: Directory
