apiVersion: v1
kind: Pod
metadata:
  name: transformer-nemo-ffmpeg
  annotations:
    # Values it can take ["hpull://","hpush://"]
    communication_type: "hpull://"
    wait_timeout: 5m
spec:
  containers:
    - name: server
      image: aistorage/transformer_nemo_ffmpeg:latest
      imagePullPolicy: IfNotPresent
      ports:
        - name: default
          containerPort: 80
      command: ['/code/server.py', '--listen', '0.0.0.0', '--port', '80']
      readinessProbe:
        httpGet:
          path: /health
          port: default
      env:
        - name: AR
          value: "16000"  # Sample rate
        - name: AC
          value: "1"     # Audio channels
        - name: ARG_TYPE
          value: ""
