apiVersion: v1
kind: Pod
metadata:
  name: transformer-nemo-ffmpeg-fqn
  annotations:
    # Values it can take ["hpull://","hpush://"]
    communication_type: "hpull://"
    wait_timeout: 5m
spec:
  containers:
    - name: server
      image: aistorage/transformer_nemo_ffmpeg:latest
      imagePullPolicy: IfNotPresent
      ports:
        - name: default
          containerPort: 80
      command: ['/code/server.py', '--listen', '0.0.0.0', '--port', '80']
      readinessProbe:
        httpGet:
          path: /health
          port: default
      env:
        - name: AR
          value: "16000"  # Sample rate
        - name: AC
          value: "1"     # Audio channels
        - name: ARG_TYPE
          value: "fqn"   # Set to "fqn" for using fully qualified name. This will open the file locally instead of making a request to the server
      # Add volume mounts and volumes for each of the disks in your targets
      volumeMounts:
        - name: sda
          mountPath: /ais/sda
        - name: sdb
          mountPath: /ais/sdb
        - name: sdc
          mountPath: /ais/sdc
        - name: sdd
          mountPath: /ais/sdd
        - name: sde
          mountPath: /ais/sde
        - name: sdf
          mountPath: /ais/sdf
        - name: sdg
          mountPath: /ais/sdg
        - name: sdh
          mountPath: /ais/sdh
        - name: sdi
          mountPath: /ais/sdi
        - name: sdj
          mountPath: /ais/sdj
  volumes:
    - name: sda
      hostPath:
        path: /ais/sda
        type: Directory
    - name: sdb
      hostPath:
        path: /ais/sdb
        type: Directory
    - name: sdc
      hostPath:
        path: /ais/sdc
        type: Directory
    - name: sdd
      hostPath:
        path: /ais/sdd
        type: Directory
    - name: sde
      hostPath:
        path: /ais/sde
        type: Directory
    - name: sdf
      hostPath:
        path: /ais/sdf
        type: Directory
    - name: sdg
      hostPath:
        path: /ais/sdg
        type: Directory
    - name: sdh
      hostPath:
        path: /ais/sdh
        type: Directory
    - name: sdi
      hostPath:
        path: /ais/sdi
        type: Directory
    - name: sdj
      hostPath:
        path: /ais/sdj
        type: Directory
