# https://github.com/NVIDIA/ais-etl/blob/master/transformers/keras_transformer/README.md
apiVersion: v1
kind: Pod
metadata:
  name: transformer-keras
  annotations:
    # Values `communication_type` can take are ["hpull://", "hrev://", "hpush://", "io://"].
    # Visit https://github.com/NVIDIA/aistore/blob/master/docs/etl.md#communication-mechanisms 
    communication_type: ${COMMUNICATION_TYPE:-"\"hpull://\""}
    wait_timeout: 10m
spec:
  containers:
    - name: server
      image: aistorage/transformer_keras:latest
      imagePullPolicy: Always
      ports:
        - name: default
          containerPort: 8000
      # change worker nodes to x2 of number of cores (cpu) available
      command:  ["gunicorn", "main:app", "--workers", "12", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000"]
      env:
        - name: FORMAT
        # expected values - PNG, JPEG, etc
          value: ${FORMAT:-"JPEG"}
        - name: TRANSFORM
        # MANDATORY: expected json string parameter-value pairs. 
        # https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image/ImageDataGenerator#apply_transform
        # e.g. '{"theta":40, "brightness":0.8, "zx":0.9, "zy":0.9}'
          value:  ${TRANSFORM}
        - name: ARG_TYPE
          value: ${ARG_TYPE:-""}
      readinessProbe:
        httpGet:
          path: /health
          port: default
      volumeMounts:
        - name: ais
          mountPath: /tmp/
  volumes:
    - name: ais
      hostPath:
        path: /tmp/
        type: Directory
