apiVersion: v1
kind: Pod
metadata:
  name: transformer-hash-with-args
  annotations:
    # Values it can take ["hpull://","hpush://"]
    communication_type: ${COMMUNICATION_TYPE:-"\"hpull://\""}
    wait_timeout: 5m
spec:
  containers:
    - name: server
      image: aistorage/transformer_hash_with_args:latest
      imagePullPolicy: Always
      ports:
        - name: default
          containerPort: 8000
      # for flask based app
      # command: ["gunicorn", "flask_server:flask_app", "--bind", "0.0.0.0:8000", "--workers", "4", "--log-level", "debug"]
      # for http based app
      # command: ["python", "http_server.py"]
      # for fastapi based app
      command: ["uvicorn", "fastapi_server:fastapi_app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4", "--no-access-log"]
      readinessProbe:
        httpGet:
          path: /health
          port: default
      env:
        - name: SEED_DEFAULT
          value: "0"
      # If using `arg_type=fqn`, ensure the `mountPath` matches the file system path 
      # where the objects are stored on AIStore targets. This allows the ETL container 
      # to access the files directly by absolute path.
  #     volumeMounts:
  #       - name: ais
  #         mountPath: /tmp/
  # volumes:
  #   - name: ais
  #     hostPath:
  #       path: /tmp/
  #       type: Directory
