name: Python Runtime Docker Images

on:
  workflow_dispatch:
  push:
    paths:
      - 'runtime/python/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Python Runtime Images
      run: |
        pushd $GITHUB_WORKSPACE/runtime
        make all
        popd
