name: Transformer Docker Images

on:
  workflow_dispatch:
    inputs:
      build_runtime_images:
        description: 'Build ETL Transformer Images'
        required: true
        type: boolean
        default: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Transformer Docker Images
      run: |
        pushd $GITHUB_WORKSPACE/transformers
        make all
        popd
